baseURL = 'https://nerdydaytrips.org/'
languageCode = 'en-gb'
title = 'Nerdy Day Trips²'
theme = "ndt2"
enableRobotsTXT = true
enableGitInfo = true

relativeURLs = true

[Permalinks]
    daytrip = "/:slug/"
    post = "/blog/:year/:month/:filename/"

[outputs]
    section = ['html', 'rss', 'json']
    home = ['html', 'rss']
    page = ['html', 'json']
    rss = ['rss']
    taxonomy = ['html', 'rss']
    term = ['html', 'rss']

[markup.goldmark.renderer]
    unsafe = true

[params]
    mainSections = ["daytrip", "post"]
    description = "A global map of places to visit that might appeal to nerdy types"

[params.repository]
  branch = 'main'
  owner = 'nerdydaytrips'
  repo = 'website'
  service = 'GitHub'
  urlPatternEdit = 'https://github.com/%s/%s/edit/%s/%s'
  urlPatternView = 'https://github.com/%s/%s/blob/%s/%s'

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[menu]
  [[menu.main]]
    name = "Search"
    url = "/search"
    title = "Search by name"
    weight = 15
    [menu.main.params]
      icon = "fa-solid fa-magnifying-glass-location"
  [[menu.main]]
    name = "Add"
    url = "https://add.nerdydaytrips.org/"
    title = "Add a new venue"
    weight = 16
    [menu.main.params]
      icon = "fa-solid fa-circle-plus"      
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    title = "Our blog"
    weight = 20
    [menu.main.params]
      icon = "fa-solid fa-blog"
  [[menu.main]]
    name = "About"
    url = "/about/"
    title = "About Nerdy Day Trips"
    weight = 30
    [menu.main.params]
      icon = "fa-solid fa-circle-info"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    title = "Contact us"
    weight = 40
    [menu.main.params]
      icon = "fa-solid fa-at"
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/nerdydaytrips/website"
    title = "Help out on GitHub!"
    weight = 50
    [menu.main.params]
      icon = "fa-brands fa-github"
