name: Flake ❄️ Lock 🔒️ Updater ✨

on:
  schedule:
    - cron: 20 04 * * 0
  workflow_dispatch:

jobs:
  lock-updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'holster'
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
